config/routes.rb
Rails.application.routes.draw do

  post 'likes/create'

  get '/ideas' => 'ideas#index'

  get 'ideas/index' => 'ideas#index'

  post 'ideas/create'

  get 'ideas/:id' => 'ideas#show'

  get 'ideas/:id/destroy' => 'ideas#destroy'

  post 'sessions/create'

  get '/signout' => 'sessions#destroy'

  resources :users

  root "users#index"

  get 'users/index'

  get 'users/create'

  get 'users/:id' => 'users#show'

  get '/ideas/users/:id' => 'users#show'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	belongs_to :user
	has_many :likes

	validates :idea, :presence => true, :length => { :in => 2..1000}
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :idea

	validates_uniqueness_of :user_id, scope: :idea_id
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :ideas
	has_many :likes
	attr_accessor :password, :password_confirmation

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name,  
			  :presence => true, 
			  :length => { :in => 2..30 }
	validates :last_name, 
			  :presence => true, 
			  :length => { :in => 2..30 }
	validates :email, 
			  :presence => true, 
			  :uniqueness => { :case_sensitive => false },
			  :format => { :with => EMAIL_REGEX }
	validates :alias, 
			  :presence => true,
			  :length => { :in => 2..30 }
	validates :password, 
			  :presence => true,
			  :confirmation => true,
			  :length => { :in => 8..100 }
	validates :password_confirmation, 
			  :presence => true

	#before the user gets added to DB, run this function
	before_save :encrypt_password 

	#this method encrypts the user's unencrypted login attempt 
	#returns true if the password is a match 
	def has_password?(submitted_password)
		self.encrypted_password == encrypt(submitted_password)
	end

	#class method that checks whethere the user's email and submitted password are valid 
	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	private
		def encrypt_password
			# generate a unique salt if it's a new user 
			# self.password uses the attr_accessor we defined above to allow me to grab the inputed password 
			self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?

			# encrypt the password and store that in the encrypted_password field 
			self.encrypted_password = encrypt(self.password) #this self.password is what's in the post data
		end

		def encrypt(password)
			Digest::SHA2.hexdigest("#{self.salt}--#{password}")
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @user = User.find(session[:user_id])
    # get all ideas only, without the likes
    all_ideas = Idea.all
    # get all ideas joined by the likes table and ordering them by the likes count
    liked_ideas = Idea.joins(:likes).group(:idea_id).order("count(likes.idea_id) DESC")
    #@ideas = Idea.all
    @ideas = liked_ideas | all_ideas

    @likes = Like.all
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      flash[:success] = 'Idea Posted!' 
      redirect_to :back
    else
      flash[:errors] = @idea.errors.full_messages 
      redirect_to :back
    end
  end

  def show
    @user = User.find(session[:user_id])
    @idea = Idea.find(params[:id])
    @likes = Like.all
  end

  def destroy
    Idea.find(params[:id]).destroy
    redirect_to :back
  end

  private 

  def idea_params
    params.require(:idea).permit(:idea, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
  		@like = Like.new(like_params)
  		@like.save
  		redirect_to :back
  	end

  	def like_params
  		params.require(:like).permit(:user_id, :idea_id)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash[:error] = 'Invalid Login Credentials'
      #if there is an error, redirect back to login
      redirect_to '/'
    else 
      #sign_in user
      session[:user_id] = user.id
      redirect_to '/ideas'
    end
  end

  def destroy
    #sign_out
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      flash[:success] = 'User was successfully created!'
      redirect_to '/' 
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to '/'
    end
  end

  def show
    @user = User.find(params[:id])
    @ideas = Idea.where(user_id: @user.id).count
    @likes = Like.where(user_id: @user.id).count
  end

  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :alias, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/index.html.erb
<h1>Welcome, <%= @user.first_name %>!</h1>
<a href="/signout">Logout</a>
<br />
<h2>Post Idea</h2>
<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p class="red"><%= error %></p>
	<% end %>
<% end %>
<% if flash[:success] %>
	<p class="green"><%= flash[:success] %></p>
<% end %>
<%= form_for( :idea, :url => ideas_create_path ) do |f| %>
	<%= f.text_area :idea %>
	<%= f.hidden_field :user_id, :value => @user.id %>
	<%= f.submit "Idea!" %>
<% end %>
<br />

<% @ideas.each do |idea| %>
 <p><a href="users/<%= idea.user.id %>"><%= idea.user.alias %></a> says:</p>
 <div class="IDEA"><%= idea.idea %></div>
 <% if idea.user.id == @user.id %>
 	<a href="/ideas/<%= idea.id %>/destroy">Delete</a>
 <% end %>
	<%= form_for( :like, :url => likes_create_path ) do |f| %>
		<%= f.hidden_field :user_id, :value => @user.id %>
		<%= f.hidden_field :idea_id, :value => idea.id %>
		<%= f.submit "Like" %>
	<% end %>
	<a href="ideas/<%= idea.id %>"><%= idea.likes.count %> people</a> like this
	<br /> 
	<hr />
<% end %>

app/views/ideas/show.html.erb
<% @idea.likes.each do |like| %>

<%= like.user.first_name %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaExam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

<%= @likes %>

app/views/users/index.html.erb
<h1>Ideas!</h1>
<div class="reg">
<h2>Register</h2>
<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p class="red"><%= error %></p>
	<% end %>
<% end %>
<% if flash[:success] %>
	<p><%= flash[:success] %></p>
<% end %>
<%= form_for @user do |f| %>

<div class="field">
	<%= f.label :first_name %><br />
	<%= f.text_field :first_name %>
</div>
<br />
<div class="field">
	<%= f.label :last_name %><br />
	<%= f.text_field :last_name %>
</div>
<br />
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<br />
<div class="field">
	<%= f.label :alias %><br />
	<%= f.text_field :alias %>
</div>
<br />
<p>*Password should be at least 8 characters</p>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>
<br />
<div class="field">
	<%= f.label "Confirm Password" %><br />
	<%= f.password_field :password_confirmation %>
</div>
<br />
<div class="actions">
    <%= f.submit "Register" %>
 </div>

<% end %>
</div>
<!-- End of Registration -->
<!--#######################################################################-->
<div class="log">
<h2>Log In</h2>
<%= flash[:error] %>
<%= form_for( :session, :url => sessions_create_path ) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <br />
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

</div>

app/views/users/show.html.erb
<a href="/signout">Logout</a>
<a href="/ideas">Ideas Dashboard</a>
<h3>Name: <%= @user.first_name %> <%= @user.last_name%></h3>
<h3>Alias: <%= @user.alias %></h3>
<h3>Email: <%= @user.email %></h3>
<hr />
<h3>Total Number of Ideas: <%= @ideas %></h3>
<h3>Total Number of Likes: <%= @likes %></h3>